version: '3.2'
services:
  frontend-v2:
    build: .
    env_file:
      - local.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
networks:
  default:
    external:
      name: speedupamerica_default
