version: 2
jobs:
  build:
    docker:
      - image: node:12.4.0-alpine
    environment:
      ENV: test
    working_directory: ~/speedupamerica-frontend
    steps:
      - checkout
      - run:
          command: |
            apk add --no-cache ca-certificates
      - run:
          command: |
            npm ci
            npm run lint
            npm run build
            npm test
      - run:
          name: "Run Mocha and Collect Coverage Reports"
          command: npm run test:coverage

      - store_artifacts:
          path: coverage
          destination: coverage
