version: 2
jobs:
  build:
    docker:
      - image: node:12.4.0-alpine
    environment:
      ENV: test
    working_directory: ~/speedupamerica-frontend
    steps:
      - checkout
      - run:
          command: |
            export DB_HOSTNAME=localhost
            export DB_PORT=3306
            export DB_USERNAME=root
            export DB_PASSWORD=password
            export DB_NAME=database
            npm ci
            npm run lint
            npm run build
            npm test
