version: 2
jobs:
  test:
    docker:
      - image: node:12.4.0-alpine
    environment:
      ENV: test
    working_directory: ~/speedupamerica-frontend
    steps:
      - checkout
      - run: |
        npm install
        npm lint     
        npm test